// function for random number generated by the game

let round = 1;
let previousNumbers = [];

function generateRandomNumber(round) {
    let number;
    if (round <= 10) {
        number = Math.floor(Math.random() * 51);
        while (checkPreviousNumbers(number, previousNumbers)) {
            number = Math.floor(Math.random() * 51);
        };
    } else if (round <= 25) {
        number = Math.floor(Math.random() * 101);
        while (checkPreviousNumbers(number, previousNumbers)) {
            number = Math.floor(Math.random() * 101);
        }
    } else {
        number = Math.floor(Math.random() * 201);
        while (checkPreviousNumbers(number, previousNumbers)) {
            number = Math.floor(Math.random() * 201);
        }
    }
    return number;
}

function checkPreviousNumbers(number, array) {
    let duplicate = false;
    array.map((num) => {
        if (num == number) duplicate = true;
    })
    return duplicate;
}